dist: bionic
language: python
python:
  - 2.7
  - 3.6
node_js:
  - 12
before_install:
  - nvm install 12
  - node --version
  - make node_deps
addons:
  apt:
    packages:
      - libevent-dev
script:
  - ( while true; do echo keep alive!; sleep 60; done ) &
  - make lint coverage bench
after_success:
  - coveralls
